apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
stringData:
  POSTGRES_USER: backend
  POSTGRES_PASSWORD: backend
  POSTGRES_DB: backend_lab
  DATABASE_URL: postgresql+asyncpg://backend:backend@postgres:5432/backend_lab
  JWT_SECRET_KEY: minikube-only-secret-change-me
  GRAFANA_ADMIN_PASSWORD: admin
